name: mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.3.3
  provider: ^6.1.1
  carousel_slider: ^5.0.0
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  video_player: ^2.10.1
  chewie: ^1.12.1
  screen_protector: ^1.4.12
  url_launcher: ^6.3.1
  syncfusion_flutter_pdfviewer: ^28.1.33
  path_provider: ^2.1.5
  razorpay_flutter: ^1.3.6
  confetti: ^0.7.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.5
  firebase_app_check: ^0.3.1+4
  flutter_local_notifications: ^18.0.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  screenshot: ^3.0.0
  gal: ^2.2.1
  permission_handler: ^11.3.1
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  audioplayers: ^6.5.1
  youtube_player_flutter: ^9.0.1
  # flutter_jailbreak_detection removed due to build incompatibility
  safe_device: ^1.1.4
  device_info_plus: ^10.1.2
  camera: ^0.10.5+5


  crypto: any
  flutter_secure_storage: ^9.0.0
  image: ^4.0.17
  share_plus: ^12.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  fl_chart: ^0.66.0
  pdf: ^3.10.8
  printing: ^5.12.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_padded.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/.env
    - assets/sound/
